### ISSUE TITLE
Camera angle should be synced

### ISSUE THREAD

**Issue by log101** [peter-kimanzi/Through-The-Space-Black-Hole#1]
It looks pretty cool! But after I 'touch' the cube and drag it around the camera angle gets reset. It could be great if the animation angle(don't know if it's the right term) and camera angle is synced. So the animation continues from where I stopped dragging.

**Comment by peter-kimanzi** [comment]
Hey Furkan, 

Thanks for your input. Just noticed this, let me try and fix it. 

Regards,
Peter.
